const lessonTitle = "没有围墙的花园";

const lessonData = [
    // ===== 第 1 段 =====
    ["米卡尔", "mǐ kǎ ěr", "Mikael", "Mikael"],
    ["是", "shì", "is", "ialah"],
    ["美国", "měi guó", "America", "Amerika"],
    ["加州", "jiā zhōu", "California", "California"],
    ["有名", "yǒu míng", "famous", "terkenal"],
    ["的", "de", "", ""],
    ["富翁", "fù wēng", "millionaire", "jutaawan"],
    ["。", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["有", "yǒu", "has", "mempunyai"],
    ["一栋", "yí dòng", "a (measure word for building)", "sebuah"],
    ["美丽", "měi lì", "beautiful", "cantik"],
    ["的", "de", "", ""],
    ["洋房", "yáng fáng", "bungalow / western-style house", "rumah banglo"],
    ["和", "hé", "and", "dan"],
    ["一座", "yí zuò", "a (measure word for garden)", "sebuah"],
    ["大", "dà", "big", "besar"],
    ["花园", "huā yuán", "garden", "taman bunga"],
    ["。", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["米卡尔", "mǐ kǎ ěr", "Mikael", "Mikael"],
    ["有", "yǒu", "has", "mempunyai"],
    ["一个", "yí gè", "a", "satu"],
    ["令", "lìng", "make / cause", "membuatkan"],
    ["自己", "zì jǐ", "himself", "dirinya sendiri"],
    ["头疼", "tóu téng", "headache / troubling", "sakit kepala / merunsingkan"],
    ["的", "de", "", ""],
    ["难题", "nán tí", "difficult problem", "masalah sukar"],
    ["：", "", "", ""],
    ["这么", "zhè me", "so / such", "begitu"],
    ["多", "duō", "much / many", "banyak"],
    ["的", "de", "", ""],
    ["财富", "cái fù", "wealth", "kekayaan"],
    ["肯定", "kěn dìng", "certainly", "pasti"],
    ["有", "yǒu", "have", "ada"],
    ["好多", "hǎo duō", "many", "ramai"],
    ["人", "rén", "people", "orang"],
    ["在", "zài", "are", "sedang"],
    ["打主意", "dǎ zhǔ yì", "have designs on / covet", "mengambil berat / berniat jahat"],
    ["。", "", "", ""],
    ["怎么", "zěn me", "how", "bagaimana"],
    ["办", "bàn", "to do / to handle", "nak buat"],
    ["呢", "ne", "particle", ""],
    ["？", "", "", ""],
    ["于是", "yú shì", "so / therefore", "maka / lalu"],
    ["米卡尔", "mǐ kǎ ěr", "Mikael", "Mikael"],
    ["让", "ràng", "let / have", "menyuruh"],
    ["工人", "gōng rén", "worker", "pekerja"],
    ["在", "zài", "at", "di"],
    ["房子", "fáng zi", "house", "rumah"],
    ["四周", "sì zhōu", "surrounding", "sekeliling"],
    ["筑起", "zhù qǐ", "build up", "mendirikan / membina"],
    ["高高", "gāo gāo", "tall / high", "tinggi"],
    ["的", "de", "", ""],
    ["围墙", "wéi qiáng", "wall / fence", "tembok / pagar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["春天", "chūn tiān", "Spring", "Musim bunga"],
    ["一到", "yí dào", "when (spring) comes", "apabila tiba"],
    ["，", "", "", ""],
    ["花园", "huā yuán", "garden", "taman"],
    ["里", "lǐ", "inside", "dalam"],
    ["鲜花", "xiān huā", "flowers", "bunga-bungaan"],
    ["怒放", "nù fàng", "in full bloom", "mekar dengan subur"],
    ["，", "", "", ""],
    ["浓香", "nóng xiāng", "strong fragrance", "bau harum yang kuat"],
    ["飘过", "piāo guò", "drift over", "berbaur melewati"],
    ["围墙", "wéi qiáng", "wall", "tembok"],
    ["，", "", "", ""],
    ["令", "lìng", "make", "membuatkan"],
    ["全镇", "quán zhèn", "the whole town", "seluruh bandar"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "orang"],
    ["都", "dōu", "all", "semua"],
    ["很", "hěn", "very", "sangat"],
    ["向往", "xiàng wǎng", "yearn for / look forward to", "tertarik / menginginkan"],
    ["。", "", "", ""],
    ["几个", "jǐ gè", "a few", "beberapa orang"],
    ["好奇", "hào qí", "curious", "ingin tahu"],
    ["的", "de", "", ""],
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["想", "xiǎng", "think", "berfikir"],
    ["：", "", "", ""],
    ["院子", "yuàn zi", "yard / courtyard", "halaman"],
    ["里", "lǐ", "inside", "dalam"],
    ["肯定", "kěn dìng", "certainly", "pasti"],
    ["种着", "zhòng zhe", "planted with", "ditanam dengan"],
    ["什么", "shén me", "something", "sesuatu"],
    ["奇花异草", "qí huā yì cǎo", "exotic flowers and rare plants", "bunga-bungaan dan tumbuhan yang aneh dan istimewa"],
    ["，", "", "", ""],
    ["听说", "tīng shuō", "heard that", "terdengar bahawa"],
    ["有", "yǒu", "there is", "ada"],
    ["一种", "yì zhǒng", "a kind of", "sejenis"],
    ["长着", "zhǎng zhe", "growing / having", "yang mempunyai"],
    ["大眼睛", "dà yǎn jīng", "big eyes", "mata yang besar"],
    ["的", "de", "", ""],
    ["花", "huā", "flower", "bunga"],
    ["还会", "hái huì", "also can", "juga boleh"],
    ["给", "gěi", "for", "kepada"],
    ["孩子们", "hái zi men", "children", "kanak-kanak"],
    ["唱歌", "chàng gē", "sing", "bernyanyi"],
    ["呢", "ne", "particle", ""],
    ["。", "", "", ""],
    ["于是", "yú shì", "so", "maka"],
    ["，", "", "", ""],
    ["孩子们", "hái zi men", "children", "kanak-kanak"],
    ["决心", "jué xīn", "determined to", "bertekad"],
    ["探个究竟", "tàn ge jiū jìng", "find out the truth", "menyiasati / mencari tahu kebenaran"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["朦胧", "méng lóng", "dim / hazy", "kabur / samar-samar"],
    ["的", "de", "", ""],
    ["夜晚", "yè wǎn", "night", "malam"],
    ["，", "", "", ""],
    ["孩子们", "hái zi men", "children", "kanak-kanak"],
    ["搭起", "dā qǐ", "set up / build", "membina"],
    ["人梯", "rén tī", "human ladder", "tangga manusia"],
    ["跳到了", "tiào dào le", "jumped into", "melompat masuk ke"],
    ["院子", "yuàn zi", "yard", "halaman"],
    ["里", "lǐ", "inside", "dalam"],
    ["，", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["在", "zài", "in", "di"],
    ["花丛", "huā cóng", "flower bushes", "rumpun bunga"],
    ["中", "zhōng", "among", "dalam"],
    ["寻找", "xún zhǎo", "search for", "mencari"],
    ["，", "", "", ""],
    ["踏坏", "tà huài", "trampled and damaged", "memijak rosak"],
    ["了", "le", "", ""],
    ["许多", "xǔ duō", "many", "banyak"],
    ["鲜花", "xiān huā", "flowers", "bunga-bungaan"],
    ["和", "hé", "and", "dan"],
    ["嫩草", "nèn cǎo", "tender grass", "rumput muda"],
    ["。", "", "", ""],
    ["后来", "hòu lái", "later", "kemudian"],
    ["，", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["被", "bèi", "by", "oleh"],
    ["仆人", "pú rén", "servant", "pembantu rumah"],
    ["发现", "fā xiàn", "discovered", "ditemui"],
    ["，", "", "", ""],
    ["赶出", "gǎn chū", "chased out", "dihalau keluar"],
    ["了", "le", "", ""],
    ["院子", "yuàn zi", "yard", "halaman"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["米卡尔", "mǐ kǎ ěr", "Mikael", "Mikael"],
    ["大为", "dà wéi", "greatly", "sangat"],
    ["光火", "guāng huǒ", "furious / enraged", "marah sekali / naik darah"],
    ["，", "", "", ""],
    ["把", "bǎ", "", ""],
    ["这事", "zhè shì", "this matter", "perkara ini"],
    ["讲给", "jiǎng gěi", "told to", "bercerita kepada"],
    ["朋友", "péng yǒu", "friend", "kawan"],
    ["听", "tīng", "listen", "dengar"],
    ["。", "", "", ""],
    ["朋友", "péng yǒu", "friend", "Kawan"],
    ["笑", "xiào", "laughed", "ketawa"],
    ["着", "zhe", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["为何", "wèi hé", "why", "kenapa"],
    ["不", "bù", "not", "tidak"],
    ["把", "bǎ", "", ""],
    ["围墙", "wéi qiáng", "wall", "tembok"],
    ["拆了", "chāi le", "tear down", "meruntuhkan / membuka"],
    ["呢", "ne", "particle", ""],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["米卡尔", "mǐ kǎ ěr", "Mikael", "Mikael"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["那", "nà", "then", "itu"],
    ["就", "jiù", "then", "maka"],
    ["无法", "wú fǎ", "cannot", "tidak dapat"],
    ["保障", "bǎo zhàng", "protect / safeguard", "menjamin / melindungi"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["财产", "cái chǎn", "property", "harta benda"],
    ["了", "le", "", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["朋友", "péng yǒu", "friend", "Kawan"],
    ["笑", "xiào", "laughed", "ketawa"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你那", "nǐ nà", "your that", "awak punya itu"],
    ["堵墙", "dǔ qiáng", "wall", "tembok"],
    ["连", "lián", "even", "pun"],
    ["一群", "yì qún", "a group of", "sekumpulan"],
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["都", "dōu", "even", "pun"],
    ["拦挡不住", "lán dǎng bú zhù", "cannot block", "tidak dapat menghalang"],
    ["，", "", "", ""],
    ["何况", "hé kuàng", "let alone", "inikan pula / tambahan lagi"],
    ["身手不凡", "shēn shǒu bù fán", "extraordinary skill", "berkemahiran luar biasa"],
    ["的", "de", "", ""],
    ["大盗", "dà dào", "robber / thief", "pencuri / perompak"],
    ["呢", "ne", "particle", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["米卡尔", "mǐ kǎ ěr", "Mikael", "Mikael"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["听从", "tīng cóng", "listened to / followed", "mendengar / mengikuti"],
    ["了", "le", "", ""],
    ["朋友", "péng yǒu", "friend", "kawan punya"],
    ["的", "de", "", ""],
    ["劝告", "quàn gào", "advice", "nasihat"],
    ["，", "", "", ""],
    ["拆掉", "chāi diào", "tore down", "meruntuhkan"],
    ["了", "le", "", ""],
    ["围墙", "wéi qiáng", "wall", "tembok"],
    ["。", "", "", ""],
    ["于是", "yú shì", "so", "Maka"],
    ["，", "", "", ""],
    ["孩子们", "hái zi men", "children", "kanak-kanak"],
    ["首先", "shǒu xiān", "first", "pertama sekali"],
    ["冲进", "chōng jìn", "rushed into", "berlari masuk ke"],
    ["了", "le", "", ""],
    ["花园", "huā yuán", "garden", "taman"],
    ["。", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["仔细", "zǐ xì", "carefully", "dengan teliti"],
    ["寻找", "xún zhǎo", "searched for", "mencari"],
    ["心中", "xīn zhōng", "in their hearts", "dalam hati"],
    ["的", "de", "", ""],
    ["神花", "shén huā", "magical flower", "bunga ajaib"],
    ["。", "", "", ""],
    ["结果", "jié guǒ", "as a result", "hasilnya"],
    ["，", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["发现", "fā xiàn", "discovered", "mendapati"],
    ["根本", "gēn běn", "at all / simply", "langsung"],
    ["没有", "méi yǒu", "no / there is no", "tiada"],
    ["什么", "shén me", "any", "apa-apa"],
    ["奇花异草", "qí huā yì cǎo", "exotic flowers", "bunga-bungaan aneh"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["米卡尔", "mǐ kǎ ěr", "Mikael", "Mikael"],
    ["把", "bǎ", "", ""],
    ["孩子们", "hái zi men", "children", "kanak-kanak"],
    ["请进", "qǐng jìn", "invited into", "menjemput masuk ke"],
    ["了", "le", "", ""],
    ["客厅", "kè tīng", "living room", "ruang tamu"],
    ["，", "", "", ""],
    ["并", "bìng", "and", "dan"],
    ["让", "ràng", "let", "membiarkan"],
    ["他们", "tā men", "them", "mereka"],
    ["美餐", "měi cān", "have a good meal", "menjamu makanan yang lazat"],
    ["了", "le", "", ""],
    ["一顿", "yí dùn", "a meal", "satu hidangan"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["对", "duì", "to", "kepada"],
    ["孩子们", "hái zi men", "children", "kanak-kanak"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["在", "zài", "in", "Di"],
    ["花园", "huā yuán", "garden", "taman"],
    ["中", "zhōng", "in", "dalam"],
    ["种下", "zhòng xià", "plant", "tanamlah"],
    ["你们", "nǐ men", "you all", "kamu semua"],
    ["心中", "xīn zhōng", "in your hearts", "dalam hati"],
    ["的", "de", "", ""],
    ["神花", "shén huā", "magical flower", "bunga ajaib"],
    ["吧", "ba", "particle", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["孩子们", "hái zi men", "children", "Kanak-kanak"],
    ["高兴", "gāo xìng", "happy", "gembira"],
    ["得", "de", "", ""],
    ["跳起来", "tiào qǐ lái", "jumped up", "melompat kegembiraan"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["跑到", "pǎo dào", "ran to", "berlari ke"],
    ["花园", "huā yuán", "garden", "taman"],
    ["里", "lǐ", "inside", "dalam"],
    ["去", "qù", "go", "pergi"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["米卡尔", "mǐ kǎ ěr", "Mikael", "Mikael"],
    ["因为", "yīn wèi", "because", "kerana"],
    ["拆掉", "chāi diào", "tore down", "meruntuhkan"],
    ["了", "le", "", ""],
    ["围墙", "wéi qiáng", "wall", "tembok"],
    ["，", "", "", ""],
    ["使", "shǐ", "so that", "menjadikan"],
    ["全镇", "quán zhèn", "the whole town", "seluruh bandar"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "orang"],
    ["都", "dōu", "all", "semua"],
    ["可以", "kě yǐ", "can", "boleh"],
    ["欣赏", "xīn shǎng", "appreciate / enjoy", "menghargai / menikmati"],
    ["花园", "huā yuán", "garden", "taman"],
    ["的", "de", "", ""],
    ["美丽", "měi lì", "beauty", "keindahan"],
    ["，", "", "", ""],
    ["所以", "suǒ yǐ", "therefore", "oleh itu"],
    ["得到", "dé dào", "received", "mendapat"],
    ["了", "le", "", ""],
    ["全镇人", "quán zhèn rén", "all townspeople", "seluruh penduduk bandar"],
    ["的", "de", "", ""],
    ["爱戴", "ài dài", "love and respect", "kasih dan hormat"],
    ["和", "hé", "and", "dan"],
    ["尊敬", "zūn jìng", "respect", "penghormatan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段

    ["一天", "yì tiān", "One day", "Suatu hari"],
    ["，", "", "", ""],
    ["一伙", "yì huǒ", "a gang of", "sekumpulan"],
    ["大盗", "dà dào", "robbers", "perompak"],
    ["潜入", "qián rù", "sneaked into", "menyusup masuk ke"],
    ["米卡尔", "mǐ kǎ ěr", "Mikael", "Mikael punya"],
    ["的", "de", "", ""],
    ["家", "jiā", "house", "rumah"],
    ["，", "", "", ""],
    ["准备", "zhǔn bèi", "prepared to", "bersiap sedia untuk"],
    ["将", "jiāng", "will", "akan"],
    ["他家", "tā jiā", "his house", "rumahnya"],
    ["洗劫一空", "xǐ jié yì kōng", "loot completely", "merompak habis-habisan"],
    ["。", "", "", ""],
    ["大盗", "dà dào", "Robbers", "Para perompak"],
    ["们", "men", "", ""],
    ["刚", "gāng", "just", "baru sahaja"],
    ["闯入", "chuǎng rù", "broke into", "menceroboh masuk"],
    ["花园", "huā yuán", "garden", "taman"],
    ["就", "jiù", "then", "pun"],
    ["被", "bèi", "by", "oleh"],
    ["守护", "shǒu hù", "guarding", "menjaga"],
    ["神花", "shén huā", "magical flowers", "bunga ajaib"],
    ["的", "de", "", ""],
    ["孩子们", "hái zi men", "children", "kanak-kanak"],
    ["发现", "fā xiàn", "discovered", "ditemui"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["小卢比", "xiǎo lú bǐ", "Little Ruby", "Ruby kecil"],
    ["赶紧", "gǎn jǐn", "hurriedly", "cepat-cepat"],
    ["跑去", "pǎo qù", "ran to", "berlari ke"],
    ["洋房", "yáng fáng", "bungalow", "rumah banglo"],
    ["报告", "bào gào", "report", "melapor"],
    ["情况", "qíng kuàng", "situation", "keadaan"],
    ["；", "", "", ""],
    ["小比尔", "xiǎo bǐ ěr", "Little Bill", "Bill kecil"],
    ["跑去", "pǎo qù", "ran to", "berlari ke"],
    ["镇上", "zhèn shàng", "town", "bandar"],
    ["通知", "tōng zhī", "notify", "memberitahu"],
    ["大人们", "dà rén men", "adults", "orang dewasa"],
    ["……", "", "", ""],
    ["结果", "jié guǒ", "as a result", "Hasilnya"],
    ["大盗", "dà dào", "robbers", "perompak-perompak"],
    ["们", "men", "", ""],
    ["被", "bèi", "were", "telah"],
    ["及时", "jí shí", "in time", "tepat pada masanya"],
    ["赶到", "gǎn dào", "arrived", "tiba"],
    ["的", "de", "", ""],
    ["米卡尔", "mǐ kǎ ěr", "Mikael", "Mikael"],
    ["和", "hé", "and", "dan"],
    ["镇上", "zhèn shàng", "town's", "bandar punya"],
    ["的", "de", "", ""],
    ["人们", "rén men", "people", "orang ramai"],
    ["擒住", "qín zhù", "captured", "ditangkap"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["并", "bìng", "and", "dan"],
    ["捆绑", "kǔn bǎng", "tied up", "diikat"],
    ["起来", "qǐ lái", "up", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段

    ["庆功宴", "qìng gōng yàn", "victory banquet", "kenduri kemenangan"],
    ["上", "shàng", "on", "di"],
    ["，", "", "", ""],
    ["米卡尔", "mǐ kǎ ěr", "Mikael", "Mikael"],
    ["对", "duì", "to", "kepada"],
    ["所有", "suǒ yǒu", "all", "semua"],
    ["人", "rén", "people", "orang"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["要", "yào", "want to", "hendak"],
    ["感谢", "gǎn xiè", "thank", "berterima kasih"],
    ["你们", "nǐ men", "you all", "kamu semua"],
    ["，", "", "", ""],
    ["你们", "nǐ men", "you", "kamu"],
    ["使", "shǐ", "made", "membuatkan"],
    ["我", "wǒ", "me", "saya"],
    ["懂得", "dǒng de", "understand", "faham"],
    ["了", "le", "", ""],
    ["一个", "yí gè", "a", "satu"],
    ["伟大", "wěi dà", "great", "agung / besar"],
    ["的", "de", "", ""],
    ["道理", "dào lǐ", "principle", "prinsip"],
    ["——", "", "", ""],
    ["这个", "zhè ge", "this", "ini"],
    ["世界", "shì jiè", "world", "dunia"],
    ["上", "shàng", "on", "di"],
    ["，", "", "", ""],
    ["只有", "zhǐ yǒu", "only", "hanya"],
    ["敞开", "chǎng kāi", "open / wide open", "terbuka luas"],
    ["的", "de", "", ""],
    ["花园", "huā yuán", "garden", "taman"],
    ["最", "zuì", "most", "paling"],
    ["安全", "ān quán", "safe", "selamat"],
    ["、", "", "", ""],
    ["最", "zuì", "most", "paling"],
    ["美丽", "měi lì", "beautiful", "cantik"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["米卡尔", "mǐ kǎ ěr", "Mikael", "Mikael"],
    ["的", "de", "", ""],
    ["话", "huà", "words", "kata-kata"],
    ["博得", "bó dé", "won / received", "mendapat"],
    ["了", "le", "", ""],
    ["所有", "suǒ yǒu", "all", "semua"],
    ["人", "rén", "people", "orang"],
    ["热烈", "rè liè", "warm", "gemuruh / hangat"],
    ["的", "de", "", ""],
    ["掌声", "zhǎng shēng", "applause", "tepukan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段

    ["其实", "qí shí", "In fact", "Sebenarnya"],
    ["，", "", "", ""],
    ["在", "zài", "in", "Di"],
    ["我们的", "wǒ men de", "our", "kita punya"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["里", "lǐ", "in", "dalam"],
    ["也", "yě", "also", "juga"],
    ["同样", "tóng yàng", "similarly", "sama"],
    ["有", "yǒu", "there are", "terdapat"],
    ["许许多多", "xǔ xǔ duō duō", "many", "banyak-banyak"],
    ["美丽", "měi lì", "beautiful", "cantik"],
    ["的", "de", "", ""],
    ["花园", "huā yuán", "gardens", "taman-taman"],
    ["。", "", "", ""],
    ["本", "běn", "originally", "Pada asalnya"],
    ["以为", "yǐ wéi", "thought", "menyangka"],
    ["封闭", "fēng bì", "close off", "menutup"],
    ["是", "shì", "is", "ialah"],
    ["最", "zuì", "most", "paling"],
    ["安全", "ān quán", "safe", "selamat"],
    ["的", "de", "", ""],
    ["做法", "zuò fǎ", "way of doing", "cara"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "tetapi"],
    ["，", "", "", ""],
    ["却", "què", "yet", "sebaliknya"],
    ["总", "zǒng", "always", "selalu"],
    ["躲不过", "duǒ bú guò", "cannot escape", "tidak dapat lari daripada"],
    ["好奇者", "hào qí zhě", "curious ones", "orang yang ingin tahu"],
    ["的", "de", "", ""],
    ["践踏", "jiàn tà", "trampling", "pijakan / kerosakan"],
    ["。", "", "", ""],
    ["或许", "huò xǔ", "perhaps", "Mungkin"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["可以", "kě yǐ", "can", "boleh"],
    ["尝试", "cháng shì", "try", "mencuba"],
    ["打开", "dǎ kāi", "open up", "membuka"],
    ["那", "nà", "that", "itu"],
    ["堵墙", "dǔ qiáng", "wall", "tembok"],
    ["，", "", "", ""],
    ["给", "gěi", "give", "memberi"],
    ["别人", "bié rén", "others", "orang lain"],
    ["一片", "yí piàn", "a", "sebidang"],
    ["灿烂", "càn làn", "bright / splendid", "cerah / indah"],
    ["的", "de", "", ""],
    ["空间", "kōng jiān", "space", "ruang"],
    ["，", "", "", ""],
    ["那么", "nà me", "then", "maka"],
    ["，", "", "", ""],
    ["别人", "bié rén", "others", "orang lain"],
    ["也会", "yě huì", "also will", "juga akan"],
    ["给", "gěi", "give", "memberi"],
    ["你", "nǐ", "you", "awak"],
    ["真心", "zhēn xīn", "sincere", "ikhlas"],
    ["的", "de", "", ""],
    ["呵护", "hē hù", "care / protection", "penjagaan / perlindungan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["漠沙", "mò shā", "Mo Sha", "Mo Sha"],
    ["《", "", "", ""],
    ["没有围墙的花园", "méi yǒu wéi qiáng de huā yuán", "The Garden Without Walls", "Taman Tanpa Tembok"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
