const lessonTitle = "父亲的手";

const lessonData = [
    // 正文第 1 段
    ["父亲的", "fù qīn de", "father's", "bapa punya"],
    ["手", "shǒu", "hand", "tangan"],
    ["很大", "hěn dà", "very big", "sangat besar"],
    ["，", "", "", ""],
    ["有", "yǒu", "has / look like", "ada / seperti"],
    ["小蒲扇", "xiǎo pú shàn", "small cattail leaf fan", "kipas daun pudar / kipas anyaman"],
    ["那么大", "nà me dà", "that big", "sebesar itu"],
    ["，", "", "", ""],
    ["每一根", "měi yì gēn", "every single", "setiap batang"],
    ["指头", "zhǐ tou", "finger", "jari"],
    ["都", "dōu", "all", "pun"],
    ["粗得", "cū de", "thick until", "sangat tebal sehingga"],
    ["好像", "hǎo xiàng", "as if / look like", "seolah-olah"],
    ["弯不过来", "wān bù guò lái", "cannot bend", "tidak boleh bengkok"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["皮肤", "pí fū", "skin", "kulit"],
    ["皱巴巴的", "zhòu bā bā de", "wrinkled / crumpled", "berkedut-kedut"],
    ["，", "", "", ""],
    ["有点儿", "yǒu diǎnr", "a bit / slightly", "sedikit"],
    ["像", "xiàng", "like", "seperti"],
    ["树皮", "shù pí", "tree bark", "kulit kayu"],
    ["，", "", "", ""],
    ["能", "néng", "can", "boleh"],
    ["不费力气地", "bú fèi lì qì de", "effortlessly", "tanpa membazir tenaga"],
    ["修剪", "xiū jiǎn", "prune / trim", "memangkas / mencantas"],
    ["果树", "guǒ shù", "fruit trees", "pokok buah-buahan"],
    ["，", "", "", ""],
    ["也能", "yě néng", "also can", "juga boleh"],
    ["把", "bǎ", "particle (object marker)", ""],
    ["一匹", "yì pǐ", "one (measure word for horse/mule)", "seekor"],
    ["不驯服的", "bù xùn fú de", "untamed / wild", "liar / tidak jinak"],
    ["骡子", "luó zi", "mule", "bagal (peranakan kuda dan keldai)"],
    ["稳稳地", "wěn wěn de", "steadily / firmly", "dengan stabil / kukuh"],
    ["套进", "tào jìn", "put into / harness", "memasang ke dalam / menyarung"],
    ["挽具", "wǎn jù", "harness", "tali abah-abah"],
    ["。", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["这双", "zhè shuāng", "this pair of", "sepasang ini"],
    ["手", "shǒu", "hands", "tangan"],
    ["还能", "hái néng", "still can", "juga boleh / masih mampu"],
    ["灵巧", "líng qiǎo", "dexterously / skillfully", "dengan cekap / mahir"],
    ["、", "", "", ""],
    ["精确地", "jīng què de", "accurately / precisely", "dengan tepat / jitu"],
    ["画", "huà", "draw", "melukis"],
    ["一个", "yí gè", "a / one", "sebuah"],
    ["正方形", "zhèng fāng xíng", "square", "segi empat sama"],
    ["。", "", "", ""],
    ["使", "shǐ", "make / cause", "menyebabkan / membuatkan"],
    ["我", "wǒ", "me", "saya"],
    ["最难忘的", "zuì nán wàng de", "most unforgettable", "paling tidak dapat dilupakan"],
    ["是", "shì", "is", "adalah"],
    ["每当", "měi dāng", "whenever / every time", "setiap kali"],
    ["这双", "zhè shuāng", "this pair of", "sepasang ini"],
    ["手", "shǒu", "hands", "tangan"],
    ["抓着", "zhuā zhe", "grabbing / holding", "memegang / mencengkam"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["肩膀", "jiān bǎng", "shoulder", "bahu"],
    ["，", "", "", ""],
    ["就会", "jiù huì", "then will", "akan terus"],
    ["让我", "ràng wǒ", "make me feel", "membuatkan saya"],
    ["感到", "gǎn dào", "feel", "berasa"],
    ["像", "xiàng", "like", "seperti"],
    ["太阳", "tài yáng", "sun", "matahari"],
    ["般的", "bān de", "like / as", "punya / sedemikian"],
    ["温暖", "wēn nuǎn", "warmth / warm", "kehangatan / hangat"],
    ["。", "", "", ""],
    ["这双", "zhè shuāng", "this pair of", "sepasang ini"],
    ["手", "shǒu", "hands", "tangan"],
    ["几乎", "jī hū", "almost / nearly", "hampir / boleh dikatakan"],
    ["能干", "néng gàn", "can do / capable", "mampu melakukan"],
    ["一切", "yí qiè", "all / everything", "segala / semua"],
    ["活儿", "huór", "work / chores", "kerja / kerja tangan"],
    ["。", "", "", ""],
    ["然而", "rán ér", "however", "Namun / bagaimanapun"],
    ["，", "", "", ""],
    ["只在", "zhǐ zài", "only in", "hanya pada"],
    ["一件事", "yí jiàn shì", "one thing / matter", "satu perkara"],
    ["上", "shàng", "on / contextually", "atas"],
    ["，", "", "", ""],
    ["这双", "zhè shuāng", "this pair of", "sepasang ini"],
    ["手", "shǒu", "hands", "tangan"],
    ["令人", "lìng rén", "make people feel", "membuatkan orang"],
    ["失望", "shī wàng", "disappointed", "kecewa"],
    ["了", "le", "particle", ""],
    ["：", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["永远", "yǒng yuǎn", "forever", "selama-lamanya"],
    ["没学会", "méi xué huì", "never learned to", "tidak pernah belajar / gagal menguasai"],
    ["写字", "xiě zì", "write words", "menulis perkataan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["父亲", "fù qīn", "father", "Ayah"],
    ["六岁", "liù suì", "six years old", "berumur enam tahun"],
    ["时", "shí", "when", "apabila / ketika"],
    ["，", "", "", ""],
    ["开始", "kāi shǐ", "started", "mula"],
    ["在", "zài", "in", "di"],
    ["小学", "xiǎo xué", "primary school", "sekolah rendah"],
    ["一年级", "yī nián jí", "First Grade / Primary 1", "Tahun 1"],
    ["读书", "dú shū", "study / read", "belajar / bersekolah"],
    ["。", "", "", ""],
    ["那时", "nà shí", "at that time", "Pada masa itu"],
    ["，", "", "", ""],
    ["课上", "kè shàng", "in class", "dalam kelas"],
    ["答错", "dá cuò", "answered incorrectly", "salah menjawab"],
    ["一题", "yì tí", "one question", "satu soalan"],
    ["，", "", "", ""],
    ["手掌", "shǒu zhǎng", "palm", "tapak tangan"],
    ["上", "shàng", "on", "atas / di atas"],
    ["就要", "jiù yào", "will have to", "akan pasti"],
    ["挨", "ái", "suffer / endure", "kena / menerima"],
    ["十下", "shí xià", "ten times (strikes)", "sepuluh kali (ketukan)"],
    ["打", "dǎ", "beating / hit", "pukulan"],
    ["。", "", "", ""],
    ["不知", "bù zhī", "do not know", "Entah mengapa / tidak tahu"],
    ["什么", "shén me", "what", "apa"],
    ["原因", "yuán yīn", "reason", "sebab"],
    ["，", "", "", ""],
    ["父亲", "fù qīn", "father", "ayah"],
    ["那", "nà", "that", "yang"],
    ["淡色", "dàn sè", "light-colored", "berwarna cerah"],
    ["头发", "tóu fa", "hair", "rambut"],
    ["下面", "xià miàn", "under / underneath", "di bawah"],
    ["的", "de", "particle", ""],
    ["脑袋", "nǎo dai", "brain / head", "kepala / otak"],
    ["怎么也", "zěn me yě", "no matter how / by no means", "bagaimanapun langsung tidak"],
    ["装不进", "zhuāng bú jìn", "cannot fit in / absorb", "tidak boleh masuk / gagal menyerap"],
    ["课上", "kè shàng", "in class", "dalam kelas"],
    ["讲的", "jiǎng de", "taught / spoken", "yang diajar"],
    ["数字", "shù zì", "numbers", "nombor"],
    ["或", "huò", "or", "atau"],
    ["要背的", "yào bèi de", "required to memorize", "yang perlu dihafal"],
    ["课文", "kè wén", "text", "teks / rencana"],
    ["。", "", "", ""],
    ["在", "zài", "in", "Di"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["才", "cái", "only", "baru sahaja"],
    ["呆了", "dāi le", "stayed", "tinggal / berada"],
    ["几个月", "jǐ gè yuè", "a few months", "beberapa bulan"],
    ["，", "", "", ""],
    ["我", "wǒ", "my", "saya punya"],
    ["爷爷", "yé ye", "paternal grandfather", "datuk"],
    ["就", "jiù", "then", "pun / terus"],
    ["领他", "lǐng tā", "led him / brought him", "membawanya"],
    ["回家", "huí jiā", "home", "pulang ke rumah"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["让他", "ràng tā", "let him", "membiarkan dia"],
    ["留在", "liú zài", "stay at", "tinggal di"],
    ["农场", "nóng chǎng", "farm", "ladang / kebun"],
    ["干", "gàn", "do / perform", "melakukan / membuat"],
    ["成年", "chéng nián", "adult", "dewasa"],
    ["男人", "nán rén", "men", "lelaki"],
    ["干的", "gàn de", "done by", "yang dilakukan oleh"],
    ["农活儿", "nóng huór", "farm work", "kerja-kerja ladang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["若干年", "ruò gān nián", "Certain years / years later", "Beberapa tahun"],
    ["后", "hòu", "later", "kemudian"],
    ["，", "", "", ""],
    ["一天", "yì tiān", "one", "suatu"],
    ["夜里", "yè lǐ", "night", "malam"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["以为", "yǐ wéi", "thought / assumed", "menyangka / mengira"],
    ["没人", "méi rén", "nobody", "tiada orang"],
    ["看见", "kàn jiàn", "saw / watching", "melihat"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "terus / lalu"],
    ["拿出", "ná chū", "took out", "mengeluarkan"],
    ["儿子", "ér zi", "son's", "anak lelaki punya"],
    ["小学", "xiǎo xué", "primary school", "sekolah rendah"],
    ["二年级", "èr nián jí", "Second Grade / Primary 2", "Tahun 2"],
    ["的", "de", "particle", ""],
    ["课本", "kè běn", "textbook", "buku teks"],
    ["，", "", "", ""],
    ["准备", "zhǔn bèi", "prepared / intended", "bersedia / berniat"],
    ["下功夫", "xià gōng fū", "make serious efforts / put in work", "berusaha sungguh-sungguh"],
    ["学些", "xué xiē", "learn some", "belajar sedikit"],
    ["单字", "dān zì", "words / characters", "perkataan / kosa kata"],
    ["。", "", "", ""],
    ["但是", "dàn shì", "but / however", "Tetapi / namun"],
    ["，", "", "", ""],
    ["不一会儿", "bù yí huì r", "in a short while / before long", "tidak lama kemudian / sekejap saja"],
    ["，", "", "", ""],
    ["父亲", "fù qīn", "father", "ayah"],
    ["不得不", "bù dé bù", "have no choice but to", "terpaksa / mahu tidak mahu"],
    ["放弃", "fàng qì", "give up", "berputus asa / melepaskan"],
    ["了", "le", "particle", ""],
    ["。", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["趴在", "pā zài", "lie face down on", "meniarap di atas / tunduk atas"],
    ["书上", "shū shàng", "on the book", "buku"],
    ["痛哭", "tòng kū", "cry bitterly / weep aloud", "menangis dengan teramat sedih / meratap"],
    ["道", "dào", "said", "dan berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["连", "lián", "even", "pun / bahkan"],
    ["孩子的", "hái zi de", "child's", "anak punya"],
    ["课本", "kè běn", "textbook", "buku teks"],
    ["都", "dōu", "even", "pun"],
    ["读不了", "dú bù liǎo", "cannot read", "tidak boleh membaca"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["从那以后", "cóng nà yǐ hòu", "From then on", "Sejak daripada itu"],
    ["，", "", "", ""],
    ["无论", "wú lùn", "no matter how", "tidak kira bagaimana"],
    ["人们", "rén men", "people", "orang ramai"],
    ["怎么", "zěn me", "how", "bagaimana"],
    ["劝他", "quàn tā", "persuade him", "memujuknya"],
    ["学习", "xué xí", "study / learn", "belajar"],
    ["，", "", "", ""],
    ["都不能", "dōu bù néng", "all could not", "tetap tidak boleh"],
    ["使他", "shǐ tā", "make him", "membuatkan dia"],
    ["坐在", "zuò zài", "sit down before", "duduk di hadapan"],
    ["笔和纸", "bǐ hé zhǐ", "pen and paper", "pen dan kertas"],
    ["面前", "miàn qián", "in front of", "muka"],
    ["了", "le", "particle", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["父亲", "fù qīn", "father", "Ayah"],
    ["当过", "dāng guò", "worked as / served as", "pernah menjadi"],
    ["农场主", "nóng chǎng zhǔ", "farmer / farm owner", "pemilik ladang"],
    ["、", "", "", ""],
    ["修路工人", "xiū lù gōng rén", "road builder", "pekerja pembina jalan"],
    ["和", "hé", "and", "dan"],
    ["工厂工人", "gōng chǎng gōng rén", "factory worker", "pekerja kilang"],
    ["。", "", "", ""],
    ["干活时", "gàn huó shí", "when working", "Ketika bekerja"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["那双", "nà shuāng", "that pair of", "sepasang itu punya"],
    ["手", "shǒu", "hands", "tangan"],
    ["从未", "cóng wèi", "never", "tidak pernah sekali-kali"],
    ["使他", "shǐ tā", "make him", "membuatkan dia"],
    ["失望过", "shī wàng guò", "disappointed", "merasa kecewa"],
    ["。", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["脑子", "nǎo zi", "brain / mind", "otak / akal"],
    ["好使", "hǎo shǐ", "bright / works well", "berfungsi dengan baik / tajam"],
    ["，", "", "", ""],
    ["有一股", "yǒu yì gǔ", "possessed a strength of", "mempunyai satu semangat"],
    ["要", "yào", "want to", "mahu"],
    ["干好活的", "gàn hǎo huó de", "do a good job's", "membuat kerja dengan baik punya"],
    ["超人", "chāo rén", "superhuman", "luar biasa / hebat"],
    ["意志", "yì zhì", "will / willpower", "tekad / azam"],
    ["。", "", "", ""],
    ["第二次世界大战", "dì èr cì shì jiè dà zhàn", "World War II", "Perang Dunia Kedua"],
    ["时", "shí", "when", "apabila / ketika"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["在", "zài", "in", "di"],
    ["一家", "yì jiā", "a (measure word for factories/companies)", "sebuah"],
    ["造船厂", "zào chuán chǎng", "shipyard", "galangan kapal / tempat bina kapal"],
    ["当", "dāng", "work as", "menjadi"],
    ["管道", "guǎn dào", "pipeline / piping", "saluran paip"],
    ["安装工", "ān zhuāng gōng", "fitter / installer", "pekerja pemasangan"],
    ["处理", "", "", ""], // 占位标记补足
    ["，", "", "", ""],
    ["安装", "ān zhuāng", "installing", "memasang"],
    ["巨型", "jù xíng", "giant / colossal", "gergasi / amat besar"],
    ["军舰", "jūn jiàn", "warship", "kapal perang"],
    ["里", "lǐ", "inside", "dalam"],
    ["复杂", "fù zá", "complex", "rumit"],
    ["、", "", "", ""],
    ["重要的", "zhòng yào de", "important", "yang penting"],
    ["零件", "líng jiàn", "components / parts", "bahagian / komponen"],
    ["。", "", "", ""],
    ["由于", "yóu yú", "due to / because of", "Oleh kerana / disebabkan"],
    ["他", "tā", "he", "dia"],
    ["工作", "gōng zuò", "work", "kerja"],
    ["劲头大", "jìn tóu dà", "with great enthusiasm / momentum", "bersemangat tinggi"],
    ["、", "", "", ""],
    ["效率高", "xiào lǜ gāo", "high efficiency", "berkecekapan tinggi"],
    ["，", "", "", ""],
    ["他的", "tā de", "his", "dia punya"],
    ["上司", "shàng sī", "boss / superior", "majikan / ketua"],
    ["指望", "zhǐ wàng", "counted on / expected to", "berharap untuk"],
    ["提拔他", "tí bá tā", "promote him", "menaikkan pangkatnya / mengangkatnya"],
    ["。", "", "", ""],
    ["然而", "rán ér", "however", "Namun"],
    ["，", "", "", ""],
    ["由于", "yóu yú", "due to", "disebabkan"],
    ["他", "tā", "he", "dia"],
    ["未能", "wèi néng", "failed to", "gagal"],
    ["通过", "tōng guò", "pass", "lulus / melepasi"],
    ["合格", "hé gé", "qualified / qualified exam", "ujian kelayakan"],
    ["考试", "kǎo shì", "examination", "peperiksaan"],
    ["而", "ér", "and thereby", "lalu"],
    ["落空了", "luò kōng le", "fell through / came to nothing", "gagal / musnah harapan"],
    ["。", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["脑子里", "nǎo zi lǐ", "in his mind", "dalam akal fikirannya"],
    ["可以", "kě yǐ", "could", "boleh"],
    ["想像出", "xiǎng xiàng chū", "visualize / imagine", "membayangkan"],
    ["通到", "tōng dào", "leading to", "menghala ke"],
    ["船的", "chuán de", "ship's", "kapal punya"],
    ["关键部位", "guān jiàn bù wèi", "key parts / crucial locations", "bahagian penting / kritikal"],
    ["的", "de", "particle", ""],
    ["条条", "tiáo tiáo", "every line of", "jaluran / setiap baris"],
    ["管道", "guǎn dào", "pipelines", "saluran paip"],
    ["；", "", "", ""],
    ["同时", "tóng shí", "at the same time", "pada masa yang sama"],
    ["，", "", "", ""],
    ["他", "tā", "his", "dia punya"],
    ["手指", "zhǐ zhǐ", "fingers", "jari-jemari"],
    ["可以在", "kě yǐ zài", "can be on", "boleh di atas"],
    ["蓝图", "lán tú", "blueprint", "cetakan biru / pelan cetak"],
    ["上", "shàng", "on", "atas"],
    ["找出", "xiǎo chū", "find out", "mencari keluar"],
    ["一条条", "yì tiáo tiáo", "lines of", "jaluran / garisan"],
    ["线路", "xiàn lù", "circuits / routes", "laluan / garisan litar"],
    ["；", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["能", "néng", "can", "boleh"],
    ["清楚地", "qīng chǔ de", "clearly", "dengan jelas"],
    ["回忆出", "huí yì chū", "recall / remember", "mengingati semula"],
    ["管道", "guǎn dào", "pipeline", "saluran paip"],
    ["上的", "shàng de", "on the", "atas punya"],
    ["每一个", "měi yí gè", "every single", "setiap satu"],
    ["拐角", "guǎi jiǎo", "corner", "sudut / selekoh"],
    ["、", "", "", ""],
    ["转弯", "zhuǎn wān", "turn / bend", "pusingan / belokan"],
    ["。", "", "", ""],
    ["然而", "rán ér", "however", "Namun"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["却", "què", "yet / surprisingly", "sebaliknya / pula"],
    ["什么", "shén me", "anything", "apa-apa pun"],
    ["都", "dōu", "all", "langsung"],
    ["读不懂", "dú bù dǒng", "cannot read / understand", "tidak boleh membaca"],
    ["、", "", "", ""],
    ["写不出", "xiě bù chū", "cannot write", "tidak boleh menulis"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["一次", "yí cì", "Once", "Suatu kali"],
    ["，", "", "", ""],
    ["母亲", "mā ma", "mother", "ibu"],
    ["去看", "qù kàn", "went to see", "pergi melawat"],
    ["我", "wǒ", "my", "saya punya"],
    ["工会", "", "", ""], // 维持原有占位对齐
    ["姨妈", "yí mā", "maternal aunt", "emak saudara"],
    ["，", "", "", ""],
    ["副", "", "", ""],
    ["父亲", "fù qīn", "father", "ayah"],
    ["到", "dào", "go to", "pergi ke"],
    ["食品店", "shí pǐn diàn", "grocery / food store", "kedai makanan / runcit"],
    ["买", "mǎi", "buy", "membeli"],
    ["水果", "shuǐ guǒ", "fruits", "buah-buahan"],
    ["。", "", "", ""],
    ["晚饭", "wǎn fàn", "dinner", "Makan malam"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["他说", "tā shuō", "he said", "dia berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["给", "gěi", "for", "untuk"],
    ["大家", "dà jiā", "everyone", "semua orang"],
    ["准备了", "zhǔn bèi le", "prepared", "menyediakan"],
    ["一些", "yì xiē", "some", "sedikit"],
    ["意想不到的", "yì xiǎng bú dào de", "unexpected", "yang tidak disangka-sangka"],
    ["水果", "shuǐ guǒ", "fruits", "buah-buahan"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["听到", "tīng dào", "heard", "mendengar"],
    ["他在", "tā zài", "he was in", "dia berada di"],
    ["厨房", "chú fáng", "kitchen", "dapur"],
    ["里", "lǐ", "inside", "dalam"],
    ["撬", "qiào", "pry open", "mengungkit / mengumpil"],
    ["铁皮罐头", "tiě pí guàn tou", "tin can / tin", "tin makanan / tin besi"],
    ["的", "de", "particle", ""],
    ["声音", "shēng yīn", "sound", "bunyi"],
    ["处理", "", "", ""],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then / afterwards", "kemudian"],
    ["，", "", "", ""],
    ["厨房", "chú fáng", "kitchen", "dapur"],
    ["里", "lǐ", "inside", "dalam"],
    ["一片", "yí piàn", "a stretch of (silence)", "suasana"],
    ["寂静", "jì jìn", "silence / quiet", "sunyi sepi"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["走到", "zǒu dào", "walked to", "berjalan ke"],
    ["门口", "mén kǒu", "doorway", "pintu masuk"],
    ["，", "", "", ""],
    ["看见", "kàn jiàn", "saw", "melihat"],
    ["他", "tā", "he", "dia"],
    ["手", "shǒu", "hand", "tangan"],
    ["拿着", "ná zhe", "holding", "sedang memegang"],
    ["空罐头", "kōng guàn tou", "empty can", "tin kosong"],
    ["，", "", "", ""],
    ["嘴里", "zuǐ lǐ", "in the mouth", "dalam mulut"],
    ["咕哝道", "gū nong dào", "mumbled / muttered", "merungut / meracau perlahan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这上面的", "zhè shàng mian de", "on this", "di atas ini punya"],
    ["画", "huà", "picture / drawing", "gambar"],
    ["太像", "tài xiàng", "too look like", "terlalu mirip / serupa dengan"],
    ["梨子", "lí zi", "pears", "buah pir"],
    ["了", "le", "particle", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["走出", "zǒu chū", "walked out", "melangkah keluar"],
    ["后门", "hòu mén", "back door", "pintu belakang"],
    ["处理", "", "", ""],
    ["，", "", "", ""],
    ["坐在", "zuò zài", "sat on", "duduk di atas"],
    ["屋外的", "wū wài de", "outside the house's", "luar rumah punya"],
    ["台阶", "tái jiē", "steps", "anak tangga"],
    ["上", "shàng", "on", "atas"],
    ["，", "", "", ""],
    ["默不作声", "mò bú zuò shēng", "silent / wordless", "berdiam diri / membisu"],
    ["处理", "", "", ""],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["进屋", "jìn wū", "entered the room", "masuk ke dalam rumah"],
    ["看到", "kàn dào", "saw", "melihat"],
    ["罐头", "guàn tou", "can", "tin itu"],
    ["上", "shàng", "on", "atas"],
    ["写着", "xiě zhe", "written with", "bercetak tulisan"],
    ["“", "", "", ""],
    ["大白土豆罐头", "dà bái tǔ dòu guàn tou", "Big White Potato Can", "Tin Kentang Putih Besar"],
    ["”", "", "", ""],
    ["设计", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],
    ["但是", "dàn shì", "but", "Namun"],
    ["那上面", "nà shàng mian", "on that top", "di atas itu"],
    ["画的", "huà de", "drawn", "gambar bercetak"],
    ["的确", "dí què", "indeed / truly", "memang benar"],
    ["像", "xiàng", "look like", "seperti / mirip"],
    ["梨", "lí", "pear", "buah pir"],
    ["，", "", "", ""],
    ["难怪", "nán guài", "no wonder", "tidak hairanlah"],
    ["副", "", "", ""],
    ["父亲", "fù qīn", "father", "ayah"],
    ["把它", "bǎ tā", "it (object particle)", "membawanya / menganggapnya"],
    ["当", "dāng", "as", "sebagai"],
    ["梨", "lí", "pear", "buah pir"],
    ["买来了", "mǎi lái le", "bought home", "membeli pulang"],
    ["结构", "", "", ""],
    ["布局", "", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["几年", "jǐ nián", "A few years", "Beberapa tahun"],
    ["后", "hòu", "later", "kemudian"],
    ["，", "", "", ""],
    ["妈妈", "mā ma", "mother", "emak"],
    ["去世了", "qù shì le", "passed away", "telah meninggal dunia"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["劝", "quàn", "persuaded / advised", "memujuk / menasihati"],
    ["父亲", "fù qīn", "father", "ayah"],
    ["来和我们", "lái hé wǒ men", "come and with us", "datang dan tinggal bersama kami"],
    ["一起住", "yì qǐ zhù", "live together", "tinggal bersama"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["不肯", "bù kěn", "unwilling", "tidak kencang / enggan"],
    ["设计", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],
    ["他的", "tā de", "his", "Dia punya"],
    ["身体", "shēn tǐ", "body / health", "kesihatan badan"],
    ["越来越差了", "yuè lái yuè chà le", "getting worse and worse", "semakin hari semakin merosot"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["轻微的", "qīng wēi de", "mild / slight", "sedikit / serangan ringan"],
    ["心脏病", "xīn zàng bìng", "heart disease / attack", "penyakit jantung"],
    ["发作", "fā zuò", "attack / onset", "menyerang"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["常常", "cháng cháng", "often", "selalu / kerap kali"],
    ["住医院", "zhù yī yuàn", "stay in hospital", "masuk hospital / dihantar ke hospital"],
    ["。", "", "", ""],
    ["格林", "gé lín", "Green (Doctor's name)", "Green"],
    ["医生", "yī shēng", "doctor", "Doktor"],
    ["每星期", "měi xīng qī", "every week", "setiap minggu"],
    ["都", "dōu", "all", "pasti"],
    ["来看他", "lai kàn tā", "come to see him", "datang melawatnya"],
    ["，", "", "", ""],
    ["给他", "gěi tā", "give him", "memberinya"],
    ["进行", "jìn xíng", "carry out / perform", "menjalankan"],
    ["治疗", "zhì liáo", "treatment / medical care", "rawatan perubatan"],
    ["。", "", "", ""],
    ["医生", "yī shēng", "doctor", "Doktor"],
    ["给了他", "gěi le tā", "gave him", "telah memberinya"],
    ["一瓶", "yì píng", "one bottle of", "sebotol"],
    ["硝酸甘油片", "xiāo suān gān yóu piàn", "nitroglycerin tablets", "ubat nitroglycerin (ubat jantung)"],
    ["设计", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],
    ["万一", "wàn yī", "just in case / in case of", "sekiranya / malang tidak berbau"],
    ["他", "tā", "he", "dia"],
    ["心脏病", "xīn zàng bìng", "heart attack", "sakit jantung"],
    ["发作", "fā zuò", "attack", "menyerang"],
    ["，", "", "", ""],
    ["让他", "ràng tā", "ask him to", "menyuruhnya"],
    ["把", "bǎ", "structural particle", ""],
    ["药片", "yào piàn", "pills", "pil ubat"],
    ["放在", "fàng zài", "place at", "meletakkan di bawah"],
    ["舌头", "shé tou", "tongue", "lidah"],
    ["底部", "dǐ bù", "bottom", "bahagian bawah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["三个星期", "sān gè xīng qī", "Three weeks", "Tiga minggu"],
    ["后", "hòu", "later", "kemudian"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["心脏病", "xīn zàng bìng", "heart attack", "penyakit jantung"],
    ["发作", "fā zuò", "attacked", "menyerang"],
    ["，", "", "", ""],
    ["与世长辞了", "yǔ shì cháng cí le", "passed away / departed from world", "meninggal dunia / menghembuskan nafas terakhir"],
    ["布局", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["我", "wǒ", "I", "Saya"],
    ["只身一人", "zhī shēn yì rén", "all by myself / alone", "sebatang kara / seorang diri"],
    ["回来", "huí lái", "returned", "pulang"],
    ["参加", "jān jiā", "attend", "menghadiri"],
    ["葬礼", "zàng lǐ", "funeral", "upacara pengebumian / majlis majlis"],
    ["。", "", "", ""],
    ["格林", "gé lín", "Green", "Green"],
    ["医生", "yī shēng", "doctor", "Doktor"],
    ["说", "shuō", "said", "berkata"],
    ["他", "tā", "he", "dia"],
    ["很难过", "hěn nán guò", "very sad", "sangat sedih"],
    ["。", "", "", ""],
    ["实际上", "shí jì shàng", "In fact / actually", "Sebenarnya / hakikatnya"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["觉得", "jué de", "felt", "berasa"],
    ["有点", "yǒu diǎn", "a bit", "sedikit"],
    ["不可思议", "bù kě sī yì", "inconceivable / unimaginable", "aneh / sukar dipercayai / pelik"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["他刚", "tā gāng", "he just", "dia baru sahaja"],
    ["给", "gěi", "for", "memberi kepada"],
    ["父亲", "fù qīn", "father", "ayah"],
    ["开了一瓶", "kāi le yì píng", "prescribed a bottle of", "menetapkan sebotol"],
    ["硝酸甘油", "xiāo suān gān yóu", "nitroglycerin", "ubat nitroglycerin"],
    ["结构", "", "", ""],
    ["布局", "", "", ""],
    ["。", "", "", ""],
    ["然而", "rán ér", "However", "Namun begitu"],
    ["，", "", "", ""],
    ["他在", "tā zài", "he on", "dia di atas"],
    ["父亲", "fù qīn", "father's", "ayah punya"],
    ["身上", "shēn shàng", "body", "badan"],
    ["却", "què", "yet / surprisingly", "sebaliknya / langsung"],
    ["没找到", "méi zhǎo dào", "did not find", "tidak menemui"],
    ["这个", "zhè ge", "this", "ini punya"],
    ["药瓶", "yào píng", "pill bottle", "botol ubat"],
    ["布局", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["觉得", "jué de", "felt", "berasa"],
    ["，", "", "", ""],
    ["如果", "rú guǒ", "if", "jika / kalau"],
    ["父亲", "fù qīn", "father", "ayah"],
    ["用了", "yòng le", "used", "menggunakan"],
    ["这药", "zhè yào", "this medicine", "ubat ini"],
    ["，", "", "", ""],
    ["大概", "dà gài", "probably", "barangkali / mungkin"],
    ["还能", "hái néng", "still can", "masih boleh"],
    ["等到", "děng dào", "wait until", "menunggu sehingga"],
    ["急救医生", "jí jiù yī shēng", "paramedic / emergency doctor", "doktor kecemasan / paramedik"],
    ["的", "de", "particle", ""],
    ["到来", "dào lái", "arrival", "ketibaan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段

    ["在", "zài", "In / at", "Di / dalam"],
    ["小教堂", "xiǎo jiào táng", "small chapel", "gereja kecil"],
    ["举行", "jǐn xíng", "hold / conduct", "mengadakan"],
    ["葬礼的", "zàng lǐ de", "funeral's", "upacara pengebumian punya"],
    ["前一小时", "qián yì xiǎo shí", "one hour before", "satu jam sebelum"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["不由自主地", "bù yóu zì zhǔ de", "involuntarily / cannot help but", "secara tidak sengaja / tanpa sedar"],
    ["来到", "lái dào", "came to", "pergi ke / datang ke"],
    ["父亲的", "fù qīn de", "father's", "ayah punya"],
    ["花园", "huā yuán", "garden", "taman bunga"],
    ["门口", "mén kǒu", "gate / entrance", "pintu masuk"],
    ["，", "", "", ""],
    ["一个", "yí gè", "a", "seorang"],
    ["邻居", "lín jū", "neighbor", "jiran tetangga"],
    ["就是", "jiù shì", "exactly", "memang"],
    ["在这儿", "zài zhèr", "here", "di sini"],
    ["发现", "fā xiàn", "discovered / found", "menemui"],
    ["他的", "tā de", "him", "dia"],
    ["结构", "", "", ""],
    ["布局", "", "", ""],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["感到", "gǎn dào", "felt", "berasa"],
    ["十分", "shí fēn", "extremely", "amat / sangat"],
    ["悲痛", "bēi tòng", "grieved / sorrowful", "sedih yang teramat / pilu"],
    ["，", "", "", ""],
    ["蹲下身", "dūn xià shēn", "squatted down", "mencangkung"],
    ["，", "", "", ""],
    ["看着", "kàn zhe", "looking at", "melihat"],
    ["父亲", "fù qīn", "father", "ayah"],
    ["生前", "shēng qián", "during his lifetime", "semasa hayatnya"],
    ["劳动过的", "láo dòng guò de", "worked's", "pernah bekerja punya"],
    ["地方", "dì fāng", "place", "tempat"],
    ["布局", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],
    ["我的", "wǒ de", "my", "Saya punya"],
    ["手", "shǒu", "hand", "tangan"],
    ["无目的地", "wú mù dì de", "aimlessly", "tanpa sebarang tujuan"],
    ["挖着", "wā zhe", "digging", "mengorek / menggali"],
    ["泥土", "ní tǔ", "soil / mud", "tanah"],
    ["时", "shí", "when", "apabila / ketika"],
    ["，", "", "", ""],
    ["碰到", "pèng dào", "touched / bumped into", "tersentuh / terkena"],
    ["一块", "yí kuài", "a piece of", "sekeping"],
    ["砖头", "zhuān tóu", "brick", "batu bata"],
    ["布局", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],
    ["我把", "bǎ wǒ", "I (object marker)", "Saya"],
    ["砖头", "zhuān tóu", "brick", "batu bata itu"],
    ["翻出来", "fān chū lái", "flipped out", "menterbalikkan keluar"],
    ["，", "", "", ""],
    ["扔到", "rēng dào", "threw to", "membuang ke"],
    ["一边", "yì biān", "one side", "tepi / sebelah"],
    ["设计", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],
    ["这时", "zhè shí", "at this moment", "Pada saat ini"],
    ["，", "", "", ""],
    ["跳入", "tiào rù", "jump into (eyes)", "menerpa masuk ke"],
    ["我眼帘的", "wǒ yǎn lián de", "my sight / eyes", "pandangan mata saya punya"],
    ["是", "shì", "was", "adalah"],
    ["一只", "yì zhī", "a", "sebuah / sebiji"],
    ["被扭歪", "bèi niǔ wāi", "twisted / distorted", "yang kemek / dipusing herot"],
    ["、", "", "", ""],
    ["砸坏", "zá huài", "smashed / crushed", "dihempas pecah / diketuk rosak"],
    ["、", "", "", ""],
    ["摔进", "shuāi jìn", "thrown into", "dicampak ke dalam"],
    ["松土", "sōng tǔ", "loose soil", "tanah gembur"],
    ["里的", "lǐ de", "inside's", "dalam punya"],
    ["塑料", "sù liào", "plastic", "plastik"],
    ["药瓶", "yào píng", "pill bottle", "botol ubat"],
    ["结构", "", "", ""],
    ["布局", "", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段

    ["我", "wǒ", "I", "Saya"],
    ["手里", "shǒu lǐ", "in hand", "di tangan"],
    ["拿着", "ná zhe", "holding", "sedang memegang"],
    ["这瓶", "zhè píng", "this bottle of", "botol ini punya"],
    ["硝酸甘油片", "xiāo suān gān yóu piàn", "nitroglycerin tablets", "ubat nitroglycerin"],
    ["，", "", "", ""],
    ["眼前", "yǎn qián", "before my eyes", "di depan mata"],
    ["浮现出", "fú xiàn chū", "emerged / floated up", "terbayang / menjelma keluar"],
    ["这样", "zhè yàng", "such a / like this", "begini punya"],
    ["一幕", "yí mù", "a scene", "satu babak / pemandangan"],
    ["情景", "qíng jǐng", "situation / scene", "situasi / keadaan"],
    ["：", "", "", ""],
    ["父亲", "fù qīn", "father", "ayah"],
    ["拚命", "pīn mìng", "desperately / with all might", "bermati-matian"],
    ["想拧开", "xiǎng nǐng kāi", "want to unscrew / open", "cuba memusing buka"],
    ["这个", "zhè ge", "this", "ini punya"],
    ["药瓶盖儿", "yào píng gài r", "bottle cap", "penutup botol ubat"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["拧不开", "nǐng bù kāi", "cannot unscrew open", "gagal dipusing buka"],
    ["；", "", "", ""],
    ["他在", "tā zài", "he in", "dia dalam"],
    ["绝望中", "jué wàng zhōng", "despair / hopelessness", "keadaan berputus asa"],
    ["处理", "", "", ""],
    ["，", "", "", ""],
    ["企图", "qǐ tú", "attempting / trying to", "cuba / berniat untuk"],
    ["用砖头", "yòng zhuān tóu", "use brick", "menggunakan batu bata"],
    ["砸开", "zá kāi", "smash open", "memecahkan buka"],
    ["这个", "zhè ge", "this", "ini punya"],
    ["塑料瓶", "sù liào píng", "plastic bottle", "botol plastik"],
    ["结构", "", "", ""],
    ["布局", "", "", ""],
    ["。", "", "", ""],
    ["随着", "suí zhe", "along with", "Seiring dengan"],
    ["泪水的", "lèi shuǐ de", "tears'", "air mata punya"],
    ["落下", "luò xià", "falling", "mengalir turun"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["知道", "zhī dào", "know", "tahu / sedar"],
    ["父亲", "fù qīn", "father", "ayah"],
    ["至死", "zhì sǐ", "until death", "sehingga menemui ajal / sampai mati"],
    ["也没能", "yě méi néng", "also failed to", "pun tidak berjaya"],
    ["拧开", "nǐng kāi", "unscrew open", "memusing buka"],
    ["这个", "zhè ge", "this", "ini punya"],
    ["药瓶", "yào píng", "pill bottle", "botol ubat"],
    ["结构", "", "", ""],
    ["布局", "", "", ""],
    ["。", "", "", ""],
    ["因为", "yīn wèi", "because", "Kerana"],
    ["药瓶盖上", "yào píng gài shàng", "on the bottle cap", "di atas penutup botol ubat"],
    ["写着", "xiě zhe", "written with", "tercetak tulisan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["防止", "fáng zhǐ", "prevent", "Halang / elakkan"],
    ["小孩", "xiǎo hái", "children", "kanak-kanak"],
    ["拧开", "nǐng kāi", "unscrew open", "daripada memusing buka"],
    ["——", "", "", ""],
    ["按下去", "àn xià qù", "press down", "tekan ke bawah"],
    ["，", "", "", ""],
    ["左拧", "zuǒ nǐng", "turn left", "pusing ke kiri"],
    ["，", "", "", ""],
    ["拔", "bá", "pull / lift", "cabut / tarik"],
    ["”", "", "", ""],
    ["结构", "", "", ""],
    ["布局", "", "", ""],
    ["。", "", "", ""],
    ["目不识丁的", "mù bù shí dīng de", "completely illiterate", "yang buta huruf langsung"],
    ["父亲", "fù qīn", "father", "ayah"],
    ["看不懂", "kàn bù dǒng", "cannot read / understand", "tidak faham membaca"],
    ["这一切", "zhè yí qiè", "all of this", "segala-galanya ini"],
    ["设计", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段 (告别段落)

    ["尽管", "jǐn guǎn", "Although / despite", "Walaupun / sungguhpun"],
    ["我", "wǒ", "I", "saya"],
    ["知道", "zhī dào", "knew", "tahu"],
    ["这样做", "zhè yàng zuò", "doing this", "berbuat begini"],
    ["是", "shì", "was", "adalah"],
    ["完全", "wán quán", "completely", "sepenuhnya / langsung"],
    ["不理智的", "bù lǐ zhì de", "irrational / unwise", "tidak rasional / tidak bijak"],
    ["，", "", "", ""],
    ["但我", "dàn wǒ", "but I", "namun saya"],
    ["还是", "hái shì", "still", "tetap"],
    ["进城", "jìn chéng", "went into town", "pergi ke bandar"],
    ["买了一支", "mǎi le yì zhī", "bought a (pen)", "membeli sebatang"],
    ["金笔", "jīn bǐ", "gold pen", "pen emas"],
    ["和", "hé", "and", "dan"],
    ["一本", "yì běn", "a (measure word for book/dictionary)", "sebuku / senaskah"],
    ["皮革包的", "pí gé bāo de", "leather-bound", "berkulit / dibalut kulit"],
    ["袖珍", "xiù zhēn", "pocket-sized / mini", "saiz poket / mini"],
    ["字典", "zì diǎn", "dictionary", "kamus"],
    ["设计", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],
    ["在向", "zài xiàng", "when towards", "ketika kepada"],
    ["父亲", "fù qīn", "father's", "ayah punya"],
    ["遗体", "yí tǐ", "remains / body", "jasad / jenazah"],
    ["告别", "gào bié", "bid farewell / saying goodbye", "mengucapkan selamat tinggal"],
    ["时", "shí", "when", "apabila / sewaktu"],
    ["，", "", "", ""],
    ["我把", "bǎ wǒ", "I (object marker)", "saya"],
    ["这两件", "zhè liǎng jiàn", "these two", "kedua-dua buah / batang benda ini"],
    ["东西", "dōng xi", "things", "barang"],
    ["放在", "fàng zài", "placed inside", "meletakkan di dalam"],
    ["他", "tā", "his", "dia punya"],
    ["手里", "shǒu lǐ", "hand", "tangan"],
    ["，", "", "", ""],
    ["这双", "zhè shuāng", "this pair of", "sepasang ini"],
    ["曾经是", "céng jīng shì", "once was", "pernah suatu masa dahulu adalah"],
    ["温暖", "wēn nuǎn", "warm", "hangat"],
    ["、", "", "", ""],
    ["灵巧", "líng qiǎo", "skillful", "mahir / cekap"],
    ["、", "", "", ""],
    ["能干", "néng gàn", "capable", "mampu melakukan kerja"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "namun"],
    ["永远", "yǒng yuǎn", "forever", "selama-lamanya"],
    ["没学会", "méi xué huì", "never learned to", "tidak pernah belajar"],
    ["写字", "xiě zì", "write words", "menulis perkataan"],
    ["的", "de", "particle", "yang"],
    ["手", "shǒu", "hand", "tangan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["加尔文·渥星顿", "jiā ěr wén · wò xīng dùn", "Calvin Worthington (Author)", "Calvin Worthington (Penulis)"],
    ["《", "", "", ""],
    ["父亲的手", "fù qīn de shǒu", "Father's Hands", "Tangan Ayah"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
